package ru.profitsw2000.simpletestsscreen.utils

const val TWO_ASSESSMENT_RIGHT_ANSWERS_PERCENTAGE = 0.7
const val THREE_ASSESSMENT_RIGHT_ANSWERS_PERCENTAGE = 0.8
const val FOUR_ASSESSMENT_RIGHT_ANSWERS_PERCENTAGE = 0.9
const val FIVE_ASSESSMENT_RIGHT_ANSWERS_PERCENTAGE = 1.0
const val TWO_ASSESSMENT = 2
const val THREE_ASSESSMENT = 3
const val FOUR_ASSESSMENT = 4
const val FIVE_ASSESSMENT = 5