package ru.profitsw2000.simpletestsscreen.utils

const val ADDITION_TEST_UNDER_TEN_RESULT_SIMPLE = 1
const val ADDITION_TEST_UNDER_TEN_RESULT_INTERMEDIATE = 2
const val ADDITION_TEST_UNDER_TEN_RESULT_COMPLEX = 3
const val ADDITION_TEST_UNDER_TEN_RESULT_HIGH_COMPLEXITY = 4
const val ADDITION_TEST_UNDER_TWENTY_RESULT_SIMPLE = 5
const val ADDITION_TEST_UNDER_TWENTY_RESULT_INTERMEDIATE = 6
const val ADDITION_TEST_UNDER_TWENTY_RESULT_COMPLEX = 7
const val ADDITION_TEST_UNDER_TWENTY_RESULT_HIGH_COMPLEXITY = 8
